services:
  vicareub2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - .venv/
    #     - action: rebuild
    #       path: ./pyproject.toml
